name: Build ClassicEditor

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Compile
        shell: powershell
        run: |
          Remove-Item build -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory build | Out-Null

          javac `
            -cp "c0.30-1.jar" `
            -d build `
            src/ClassicEditor.java `
            src/ClassicEditorGUI.java `
            src/LevelIO.java `
            src/LevelConverter.java `
            src/NBTReader.java `
            src/SerializationReader.java

      - name: Build JAR
        shell: powershell
        run: |
          @"
          Manifest-Version: 1.0
          Main-Class: ClassicEditorGUI
          Class-Path: c0.30-1.jar
          "@ | Set-Content -Encoding ASCII MANIFEST.MF

          jar cfm ClassicEditor.jar MANIFEST.MF -C build .

      - name: Create icon
        shell: powershell
        run: |
          python -m pip install Pillow

          python -c "from PIL import Image; Image.open('logo.png').convert('RGBA').save('logo.ico', format='ICO', sizes=[(256,256),(128,128),(64,64),(48,48),(32,32),(16,16)])"

      - name: Prepare
        shell: powershell
        run: |
          Remove-Item package -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path package\input | Out-Null

          Copy-Item ClassicEditor.jar package\input\
          Copy-Item c0.30-1.jar package\input\

      - name: Build EXE
        shell: powershell
        run: |
          Remove-Item output -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory output | Out-Null

          jpackage `
            --type exe `
            --name ClassicEditor `
            --input package\input `
            --main-jar ClassicEditor.jar `
            --main-class ClassicEditorGUI `
            --icon logo.ico `
            --dest output `
            --app-version 0.0.1.1 `
            --vendor "MarcioGames-pixel" `
            --description "Save editor for Minecraft Classic and older Java versions." `
            --win-menu `
            --win-shortcut

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ClassicEditor-Windows
          path: |
            ClassicEditor.jar
            output/*.exe
            logo.ico
